image:
  name: ghcr.io/platform-mesh/generic-resource-ui
  tag: v0.1.8
  pullPolicy: IfNotPresent

gatewayApi:
  httpRoute:
    parentRefs:
    - name: k8sapi-gateway
      namespace: platform-mesh-system
