apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../example-data-sharded

patches:
  - target:
      kind: PlatformMesh
      name: platform-mesh
      namespace: platform-mesh-system
    patch: |-
      - op: replace
        path: /spec/values/services/infra/values/kcp/shards
        value:
          - name: triton
            hostname: triton.kcp.localhost
          - name: nereus
            hostname: nereus.kcp.localhost
