{{- if and .Values.webhooks.enabled .Values.webhooks.register -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "common.entity.name" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "common.entity.name" . }}-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "common.entity.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: "/mutate-core-platform-mesh-io-v1alpha1-idpregistration"
      port: {{ .Values.webhooks.port }}
  failurePolicy: Fail
  name: midpregistration.kb.io
  rules:
  - apiGroups:
    - core.platform-mesh.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - idpregistrations
  sideEffects: None
{{- end -}}
