# delete the middleware when portal is ready
{{- if .Values.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.entity.name" . }}-strip-graphql
  namespace: {{ .Release.Namespace }}
spec:
  replacePathRegex:
    regex: ^(.+)/graphql$
    replacement: ${1}
{{- end }}
