apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-operator.name" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "keycloak-operator.selectorLabels" . | nindent 4 }}
